version: "3.7"
services:
  backend:
    build: "./backend"
    container_name: node-container
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - "./backend:/usr/src/app"
  webapp:
    build: "./webapp"
    container_name: react-container
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./webapp:/usr/src/app"
    depends_on:
      - backend
